insert into teams (name, short_name, flag_path, group_name) values ('Mexiko', 'MEX', '/flags/mexico.svg', 'A');
insert into teams (name, short_name, flag_path, group_name) values ('Südafrika', 'RSA', '/flags/south-africa.svg', 'A');
insert into teams (name, short_name, flag_path, group_name) values ('Republik Korea', 'KOR', '/flags/south-korea.svg', 'A');
insert into teams (name, short_name, flag_path, group_name) values ('Tschechien', 'CZE', '/flags/czechia.svg', 'A');
insert into teams (name, short_name, flag_path, group_name) values ('Kanada', 'CAN', '/flags/canada.svg', 'B');
insert into teams (name, short_name, flag_path, group_name) values ('Bosnien und Herzegowina', 'BIH', '/flags/bosnia-and-herzegovina.svg', 'B');
insert into teams (name, short_name, flag_path, group_name) values ('Katar', 'QAT', '/flags/qatar.svg', 'B');
insert into teams (name, short_name, flag_path, group_name) values ('Schweiz', 'SUI', '/flags/switzerland.svg', 'B');
insert into teams (name, short_name, flag_path, group_name) values ('Brasilien', 'BRA', '/flags/brazil.svg', 'C');
insert into teams (name, short_name, flag_path, group_name) values ('Marokko', 'MAR', '/flags/morocco.svg', 'C');
insert into teams (name, short_name, flag_path, group_name) values ('Haiti', 'HAI', '/flags/haiti.svg', 'C');
insert into teams (name, short_name, flag_path, group_name) values ('Schottland', 'SCO', '/flags/scotland.svg', 'C');
insert into teams (name, short_name, flag_path, group_name) values ('USA', 'USA', '/flags/united-states.svg', 'D');
insert into teams (name, short_name, flag_path, group_name) values ('Paraguay', 'PAR', '/flags/paraguay.svg', 'D');
insert into teams (name, short_name, flag_path, group_name) values ('Australien', 'AUS', '/flags/australia.svg', 'D');
insert into teams (name, short_name, flag_path, group_name) values ('Türkei', 'TUR', '/flags/turkey.svg', 'D');
insert into teams (name, short_name, flag_path, group_name) values ('Deutschland', 'GER', '/flags/germany.svg', 'E');
insert into teams (name, short_name, flag_path, group_name) values ('Curaçao', 'CUW', '/flags/curacao.svg', 'E');
insert into teams (name, short_name, flag_path, group_name) values ('Elfenbeinküste', 'CIV', '/flags/ivory-coast.svg', 'E');
insert into teams (name, short_name, flag_path, group_name) values ('Ecuador', 'ECU', '/flags/ecuador.svg', 'E');
insert into teams (name, short_name, flag_path, group_name) values ('Niederlande', 'NED', '/flags/netherlands.svg', 'F');
insert into teams (name, short_name, flag_path, group_name) values ('Japan', 'JPN', '/flags/japan.svg', 'F');
insert into teams (name, short_name, flag_path, group_name) values ('Schweden', 'SWE', '/flags/sweden.svg', 'F');
insert into teams (name, short_name, flag_path, group_name) values ('Tunesien', 'TUN', '/flags/tunisia.svg', 'F');
insert into teams (name, short_name, flag_path, group_name) values ('Belgien', 'BEL', '/flags/belgium.svg', 'G');
insert into teams (name, short_name, flag_path, group_name) values ('Ägypten', 'EGY', '/flags/egypt.svg', 'G');
insert into teams (name, short_name, flag_path, group_name) values ('IR Iran', 'IRN', '/flags/iran.svg', 'G');
insert into teams (name, short_name, flag_path, group_name) values ('Neuseeland', 'NZL', '/flags/new-zealand.svg', 'G');
insert into teams (name, short_name, flag_path, group_name) values ('Spanien', 'ESP', '/flags/spain.svg', 'H');
insert into teams (name, short_name, flag_path, group_name) values ('Kap Verde', 'CPV', '/flags/cape-verde.svg', 'H');
insert into teams (name, short_name, flag_path, group_name) values ('Saudi-Arabien', 'KSA', '/flags/saudi-arabia.svg', 'H');
insert into teams (name, short_name, flag_path, group_name) values ('Uruguay', 'URU', '/flags/uruguay.svg', 'H');
insert into teams (name, short_name, flag_path, group_name) values ('Frankreich', 'FRA', '/flags/france.svg', 'I');
insert into teams (name, short_name, flag_path, group_name) values ('Senegal', 'SEN', '/flags/senegal.svg', 'I');
insert into teams (name, short_name, flag_path, group_name) values ('Irak', 'IRQ', '/flags/iraq.svg', 'I');
insert into teams (name, short_name, flag_path, group_name) values ('Norwegen', 'NOR', '/flags/norway.svg', 'I');
insert into teams (name, short_name, flag_path, group_name) values ('Argentinien', 'ARG', '/flags/argentina.svg', 'J');
insert into teams (name, short_name, flag_path, group_name) values ('Algerien', 'ALG', '/flags/algeria.svg', 'J');
insert into teams (name, short_name, flag_path, group_name) values ('Österreich', 'AUT', '/flags/austria.svg', 'J');
insert into teams (name, short_name, flag_path, group_name) values ('Jordanien', 'JOR', '/flags/jordan.svg', 'J');
insert into teams (name, short_name, flag_path, group_name) values ('Portugal', 'POR', '/flags/portugal.svg', 'K');
insert into teams (name, short_name, flag_path, group_name) values ('DR Kongo', 'COD', '/flags/dr-congo.svg', 'K');
insert into teams (name, short_name, flag_path, group_name) values ('Usbekistan', 'UZB', '/flags/uzbekistan.svg', 'K');
insert into teams (name, short_name, flag_path, group_name) values ('Kolumbien', 'COL', '/flags/colombia.svg', 'K');
insert into teams (name, short_name, flag_path, group_name) values ('England', 'ENG', '/flags/england.svg', 'L');
insert into teams (name, short_name, flag_path, group_name) values ('Kroatien', 'CRO', '/flags/croatia.svg', 'L');
insert into teams (name, short_name, flag_path, group_name) values ('Ghana', 'GHA', '/flags/ghana.svg', 'L');
insert into teams (name, short_name, flag_path, group_name) values ('Panama', 'PAN', '/flags/panama.svg', 'L');
